### PR TITLE
improved page accessibility

### PR DESCRIPTION
**Pull request by SriramBharadwaj1**
-> added alt attributes to images in "news and events" section 
-> put socials icons in footer section in ul tag

### CODE REVIEW

**Comment by RohitKV1n0d** [comment]
@SriramBharadwaj1 May i know who this is ?

**Comment by SriramBharadwaj1** [comment]
my name is Sriram Bharadwaj, and I am starting out with open source on github. I came across your website when i was searching for codebases on HTML .
please excuse me if my methods were unconventional and I did not make a pr in the standard way, I am completely new to this, 

my email id is : sriram9217@gmail.com

**Comment by RohitKV1n0d** [comment]
Hello @SriramBharadwaj1 ,
Thank you but we can't make the changes you are requesting, this repo is private and only client approved change are to be merged to main, so i am sorry we can't do it.

**Comment by SriramBharadwaj1** [comment]
oh, I understand. 
sorry for that, I shall look into the description before contributing.
all the best with your project

**Pull request closed without merging**
